// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/meals": {
            "get": {
                "description": "Get meal information for a specific school and date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meals"
                ],
                "summary": "Get school meals",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Education office code",
                        "name": "org_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "School code",
                        "name": "school_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYYMMDD format)",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Meal"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schools": {
            "get": {
                "description": "Get all schools",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schools"
                ],
                "summary": "Get all schools",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.School"
                            }
                        }
                    }
                }
            }
        },
        "/timetables": {
            "get": {
                "description": "Get timetable for a specific school, grade, and class",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Timetables"
                ],
                "summary": "Get school timetables",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Education office code",
                        "name": "org_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "School code",
                        "name": "school_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Grade",
                        "name": "grade",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Class",
                        "name": "class",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYYMMDD format)",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "main.Meal": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/main.MealData"
            }
        },
        "main.MealData": {
            "type": "object",
            "properties": {
                "calories": {
                    "type": "number"
                },
                "menu": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "main.School": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "org_code": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "MySchool API",
	Description:      "Simple and clean school meal/timetable API server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
